name: "Test"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        # Still 22.11 here because nix-linter is broken 23.05
        nix_path: nixpkgs=channel:nixos-22.11
    - run: ./lint.sh

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - run: mkdir -p ~/.local/state/nix/profiles # required as of 23.05 ; not sure why though...
    - run: nix run home-manager/release-23.05 -- build --flake .#test
